Implementing Feedback After The First Checkpoint Defence
andela-anwosu/inverted-index-cp1 pull request #5
Opened 2017-02-07 03:28 UTC by andela-anwosu

2017-02-07 09:11 UTC, andela-kakpobome requested changes
Fix all these issues.

2017-02-07 09:11 UTC, andela-kakpobome commented on jasmine/spec/bundle.js
>  const emptyFile = require('./test/emptyFile.json');
### Critical

Files that are generated from other files should not be added to version control, eg a bundled file

2017-02-07 09:11 UTC, andela-kakpobome commented on jasmine/spec/bundle.js
> +  it('reads a JSON file and asserts that it not empty',
### Nitpick

This should be `it's not empty`

2017-02-07 09:11 UTC, andela-kakpobome commented on jasmine/spec/bundle.js
> +    expect(invertedIndexTest.validFiles(emptyFile)[1])
### Critical

I already gave you feedback on this to return an object shaped like so:

```
{
  "status": true,
  "statusMessage": "Some message"
}
```
That'll make your code more readable. Then you'ld have something like, `.validFiles(emptyFile).status.toBe('Error, empty file')`

2017-02-07 09:11 UTC, andela-kakpobome commented on jasmine/spec/bundle.js
> +    expect(invertedIndexTest.createIndex('books.json', validBook)['books.json']
### Critical

Create Index should not return anything (maybe except a Boolean), this should instead set an internal variable that `getIndex` returns when called.

2017-02-07 09:11 UTC, andela-kakpobome commented on jasmine/spec/bundle.js
> +    expect(invertedIndexTest.getIndex()['booky.json'].of)
### Critical

`getIndex` when passed a filename, should return the index for that file. That'ld be preferable to what you've done(return the entire index before plucking it out).

2017-02-07 09:11 UTC, andela-kakpobome commented on jasmine/spec/bundle.js
> +  it('returns the correct objects indices that contain the searched words',
### Nitpick

Should be `that contains`

2017-02-07 09:11 UTC, andela-kakpobome commented on src/inverted-index.js
> +      // console.log(singleBook);
### Critical

Why is this here?

2017-02-07 09:11 UTC, andela-kakpobome commented on src/inverted-index.js
> +    books.forEach((singleBook, inex) => {
### Critical

Please use reasonable variable names, `inex` does not make sense.

2017-02-07 09:11 UTC, andela-kakpobome commented on src/inverted-index.js
> +   * returns created index
### Nitpick

The rest of the doc blocks have the name of the method, why is this one exempt?

2017-02-07 09:11 UTC, andela-kakpobome commented on src/inverted-index.js
> +      for (let word = 0; word < terms.length; word += 1) {
### Critical

Stick with the `forEach` API instead.

2017-02-07 09:17 UTC, andela-kakpobome commented
@andela-anwosu your [Angular code base](https://github.com/andela-anwosu/inverted-index-cp1/blob/29ca913f887d360367230995084063f5a8e8c71e/controllers/app.js) is also riddled with `console.logs`, `alerts` and `// commented out code`.

Rethink and refactor accordingly.

2017-02-07 16:28 UTC, andela-anwosu commented on src/inverted-index.js
> +      for (let word = 0; word < terms.length; word += 1) {
completer

2017-02-07 16:32 UTC, andela-anwosu commented on jasmine/spec/bundle.js
>  const emptyFile = require('./test/emptyFile.json');
fixed

2017-02-07 16:32 UTC, andela-anwosu commented on jasmine/spec/bundle.js
> +  it('reads a JSON file and asserts that it not empty',
fixed

2017-02-07 16:32 UTC, andela-anwosu commented on jasmine/spec/bundle.js
> +    expect(invertedIndexTest.validFiles(emptyFile)[1])
fixed

2017-02-07 16:32 UTC, andela-anwosu commented on jasmine/spec/bundle.js
> +    expect(invertedIndexTest.createIndex('books.json', validBook)['books.json']
fixed

2017-02-07 16:32 UTC, andela-anwosu commented on jasmine/spec/bundle.js
> +    expect(invertedIndexTest.getIndex()['booky.json'].of)
fixed

2017-02-07 16:33 UTC, andela-anwosu commented on jasmine/spec/bundle.js
> +  it('returns the correct objects indices that contain the searched words',
completed

2017-02-07 16:33 UTC, andela-anwosu commented on src/inverted-index.js
> +      // console.log(singleBook);
fixed

2017-02-07 16:33 UTC, andela-anwosu commented on src/inverted-index.js
> +    books.forEach((singleBook, inex) => {
fixed. Now bookIndex

2017-02-07 16:33 UTC, andela-anwosu commented on src/inverted-index.js
> +   * returns created index
fixed

2017-02-08 09:03 UTC, andela-kakpobome requested changes
@andela-anwosu yet again, fix these issues!

2017-02-08 09:03 UTC, andela-kakpobome commented on controllers/app.js
> +    if (typeof (fileDoc !== 'Blob')) {
### Critical

The `typeof` here serves absolutely no purpose, why is it here?

2017-02-08 09:03 UTC, andela-kakpobome commented on controllers/app.js
> +          alert($scope.validationResult.statusMessage); // eslint-disable-line no-alert
### Critical

There are still alerts, why???????!!!!!!

2017-02-08 09:03 UTC, andela-kakpobome commented on controllers/app.js
>          // let file = $scope.indexToBeSearched || null,
### Critical

@andela-anwosu you are still really careless with things like this (commented out code), why?!

2017-02-08 09:03 UTC, andela-kakpobome commented on controllers/app.js
> +      if ($scope.indexToBeSearched === undefined) {
### Critical

Why is this not on the same line with `else`? Use an `else if`

2017-02-08 09:03 UTC, andela-kakpobome commented on jasmine/spec/inverted-index-test.js
> +    expect(invertedIndexTest.getIndex()['books.json']
### Critical

You only corrected `.getIndex()['books.json']` in one instance, you should pass `books.json` as an argument!

2017-02-08 12:00 UTC, andela-anwosu commented on controllers/app.js
> +          alert($scope.validationResult.statusMessage); // eslint-disable-line no-alert
fixed. I mentioned it yesterday that the errors were for just error messages. Taken them out now and they display just beneath the upload button.

2017-02-08 12:00 UTC, andela-anwosu commented on controllers/app.js
> +    if (typeof (fileDoc !== 'Blob')) {
fixed

2017-02-09 11:05 UTC, closed without merging